# Generated by Django 6.0.2 on 2026-03-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('Rejected', 'rejected')], default='Pending', max_length=20),
        ),
    ]
