# Generated by Django 6.0.2 on 2026-03-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
