# Generated by Django 6.0.2 on 2026-03-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('medium', 'Medium'), ('High', 'high')], max_length=20),
        ),
    ]
