# Generated by Django 6.0.2 on 2026-03-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
